# Generated by Django 4.0.5 on 2022-08-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_createstockgrp_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createstockgrp',
            name='alias',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='createstockgrp',
            name='under',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='StockGroup',
        ),
    ]
