# Generated by Django 4.0.5 on 2022-08-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_createstockgrp_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createstockgrp',
            name='quantities',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='createstockgrp',
            name='under',
            field=models.CharField(max_length=100),
        ),
    ]
