# Generated by Django 4.0.5 on 2022-08-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_createstockgrp_quantities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('under', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('gst', models.CharField(max_length=100)),
                ('supply', models.CharField(max_length=100)),
                ('rduty', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
                ('per', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
