# Generated by Django 4.0.5 on 2022-08-22 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_createstockitem_under'),
    ]

    operations = [
        migrations.CreateModel(
            name='group_ananysis_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('iquantity', models.IntegerField()),
                ('ieff_rate', models.IntegerField()),
                ('ivalue', models.IntegerField()),
                ('oquantity', models.IntegerField()),
                ('oeff_rate', models.IntegerField()),
                ('ovalue', models.IntegerField()),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.createstockgrp')),
            ],
        ),
    ]
