# Generated by Django 4.0.5 on 2022-08-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_group_ananysis_view_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_ananysis_view',
            name='ieff_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='group_ananysis_view',
            name='iquantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='group_ananysis_view',
            name='ivalue',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='group_ananysis_view',
            name='oeff_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='group_ananysis_view',
            name='oquantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='group_ananysis_view',
            name='ovalue',
            field=models.IntegerField(null=True),
        ),
    ]
