# Generated by Django 4.0.5 on 2022-08-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_group_ananysis_view_ieff_rate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='group_ananysis_view',
        ),
    ]
