# Generated by Django 4.0.5 on 2022-08-22 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_group_ananysis_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_ananysis_view',
            name='particular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.createstockgrp'),
        ),
    ]
