# Generated by Django 4.0.5 on 2022-08-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_group_ananysis_view_particular'),
    ]

    operations = [
        migrations.DeleteModel(
            name='group_ananysis_view',
        ),
    ]
