# Generated by Django 4.0.5 on 2022-08-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_group_ananysis_view_ananysis_view'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ananysis_view',
            new_name='analysis_view',
        ),
    ]
