# Generated by Django 4.0.5 on 2022-08-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_analysis_view_particular'),
    ]

    operations = [
        migrations.DeleteModel(
            name='analysis_view',
        ),
    ]
