# Generated by Django 4.0.5 on 2022-08-24 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_remove_analysis_view_stgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='godown_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('itm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.createstockitem')),
            ],
        ),
    ]
