# Generated by Django 4.0.5 on 2022-08-24 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_category_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_model',
            name='itm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.createstockitem'),
            preserve_default=False,
        ),
    ]
