# Generated by Django 4.0.5 on 2022-08-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_category_model_itm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createstockitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
